apiVersion: apps/v1
kind: Deployment
metadata:
  name: parameta-devops-mvp
  labels:
    app: parameta-devops-mvp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parameta-devops-mvp
  template:
    metadata:
      labels:
        app: parameta-devops-mvp
    spec:
      containers:
        - name: app
          image: parameta/devops-mvp:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: parameta-devops-mvp
spec:
  type: ClusterIP
  selector:
    app: parameta-devops-mvp
  ports:
    - port: 80
      targetPort: 8000
