groups:
  - name: parameta-devops-mvp-alerts
    rules:
      - alert: ServiceUnavailable
        expr: kube_deployment_status_replicas_available{deployment="parameta-devops-mvp"} < 1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Parameta DevOps MVP deployment has no available replicas"
          description: "The deployment parameta-devops-mvp does not have any available replicas for more than two minutes."
      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{job="parameta-devops-mvp", status=~"5.."}[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected on the Parameta DevOps MVP service"
          description: "More than zero HTTP 5xx responses per second were observed for five minutes."
